### ISSUE TITLE
连接到 plugin.github_connector.backend.name

### ISSUE THREAD

**Issue by shzy2012** [answerdev/plugins#11]
Github登录插件显示：

<img width="599" alt="image" src="https://github.com/answerdev/plugins/assets/3347060/54263189-5c62-4a00-b799-de8deab2f889">

如何显示自定义名称？

**Comment by shzy2012** [comment]
> @shzy2012 May I ask which version of the docker image you are using that is causing this issue?
<img width="1104" alt="image" src="https://github.com/answerdev/plugins/assets/3347060/d308c745-5e1f-4dc2-b669-40d971f40054">

我是通过answer源码中引用插件的方式编译的answer bin运行的

**Comment by shzy2012** [comment]
我试了一下两种方式：结果都不行

```
  plugins:
    login: 登录
    qrcode_login_tip: 请使用 {{ agentName }} 扫描二维码并登录。
    login_failed_email_tip: 登录失败，请允许此应用访问您的邮箱信息，然后重试。
    oauth:
      connect: 连接到 {{ auth_name }}
      remove: 移除 {{ auth_name }}
    github_connector:
      backend:
          name: Github
```

```
  plugins:
    login: 登录
    qrcode_login_tip: 请使用 {{ agentName }} 扫描二维码并登录。
    login_failed_email_tip: 登录失败，请允许此应用访问您的邮箱信息，然后重试。
    oauth:
      connect: 连接到 {{ auth_name }}
      remove: 移除 {{ auth_name }}
    github_connector:
      backend:
        info:
          name: Github
```


后台插件管理页面提示的路径是：plugin.github_connector.backend.info.name

<img width="978" alt="image" src="https://github.com/answerdev/plugins/assets/3347060/a354256f-2afe-4c59-9b81-1d877cfd1628">
